/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedSurveyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "authorizeViewer"
      | "authorizeViewerWithRole"
      | "authorizedViewers"
      | "closeSurvey"
      | "extendDeadline"
      | "getAllEncryptedTallies"
      | "getEncryptedTally"
      | "getOptionLabel"
      | "getResultSummary"
      | "getSurveyMetadata"
      | "getSurveyStats"
      | "getTopOptions"
      | "getUserVotes"
      | "getViewerDetails"
      | "hasResponded"
      | "hasValidAccess"
      | "isActive"
      | "optionsCount"
      | "protocolId"
      | "reopenSurvey"
      | "revokeViewer"
      | "submitBatchResponse"
      | "submitResponse"
      | "surveyDeadline"
      | "surveyDescription"
      | "surveyTitle"
      | "withdrawAndResubmit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchResponseSubmitted"
      | "ResponseSubmitted"
      | "SurveyActivated"
      | "SurveyClosed"
      | "ViewerAuthorized"
      | "VoteUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "authorizeViewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeViewerWithRole",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedViewers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeSurvey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "extendDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllEncryptedTallies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTally",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOptionLabel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResultSummary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSurveyMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSurveyStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTopOptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVotes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getViewerDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasResponded",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasValidAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "optionsCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reopenSurvey",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeViewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBatchResponse",
    values: [BigNumberish[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "submitResponse",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "surveyDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "surveyDescription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "surveyTitle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAndResubmit",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizeViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeViewerWithRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedViewers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closeSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllEncryptedTallies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTally",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOptionLabel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResultSummary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSurveyMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSurveyStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTopOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getViewerDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasResponded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasValidAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "optionsCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reopenSurvey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeViewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitBatchResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surveyDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surveyDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "surveyTitle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAndResubmit",
    data: BytesLike
  ): Result;
}

export namespace BatchResponseSubmittedEvent {
  export type InputTuple = [
    respondent: AddressLike,
    optionIndices: BigNumberish[],
    totalVotes: BigNumberish
  ];
  export type OutputTuple = [
    respondent: string,
    optionIndices: bigint[],
    totalVotes: bigint
  ];
  export interface OutputObject {
    respondent: string;
    optionIndices: bigint[];
    totalVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResponseSubmittedEvent {
  export type InputTuple = [respondent: AddressLike, optionIndex: BigNumberish];
  export type OutputTuple = [respondent: string, optionIndex: bigint];
  export interface OutputObject {
    respondent: string;
    optionIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyActivatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SurveyClosedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ViewerAuthorizedEvent {
  export type InputTuple = [viewer: AddressLike];
  export type OutputTuple = [viewer: string];
  export interface OutputObject {
    viewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteUpdatedEvent {
  export type InputTuple = [
    respondent: AddressLike,
    oldOptions: BigNumberish[],
    newOptions: BigNumberish[]
  ];
  export type OutputTuple = [
    respondent: string,
    oldOptions: bigint[],
    newOptions: bigint[]
  ];
  export interface OutputObject {
    respondent: string;
    oldOptions: bigint[];
    newOptions: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EncryptedSurvey extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedSurvey;
  waitForDeployment(): Promise<this>;

  interface: EncryptedSurveyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  authorizeViewer: TypedContractMethod<
    [viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizeViewerWithRole: TypedContractMethod<
    [viewer: AddressLike, role: BigNumberish, expiryTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizedViewers: TypedContractMethod<[], [string[]], "view">;

  closeSurvey: TypedContractMethod<[], [void], "nonpayable">;

  extendDeadline: TypedContractMethod<
    [newDeadline: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllEncryptedTallies: TypedContractMethod<[], [string[]], "view">;

  getEncryptedTally: TypedContractMethod<
    [optionIndex: BigNumberish],
    [string],
    "view"
  >;

  getOptionLabel: TypedContractMethod<
    [optionIndex: BigNumberish],
    [string],
    "view"
  >;

  getResultSummary: TypedContractMethod<
    [],
    [
      [bigint[], string[], bigint] & {
        optionIndices: bigint[];
        optionLabels: string[];
        totalParticipants: bigint;
      }
    ],
    "view"
  >;

  getSurveyMetadata: TypedContractMethod<
    [],
    [
      [string, string, bigint, boolean, bigint, string, bigint] & {
        title: string;
        description: string;
        optionCount: bigint;
        active: boolean;
        deadline: bigint;
        adminAddr: string;
        viewerCount: bigint;
      }
    ],
    "view"
  >;

  getSurveyStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalOptions: bigint;
        activeStatus: bigint;
        deadline: bigint;
        participantCount: bigint;
      }
    ],
    "view"
  >;

  getTopOptions: TypedContractMethod<[count: BigNumberish], [bigint[]], "view">;

  getUserVotes: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  getViewerDetails: TypedContractMethod<
    [viewer: AddressLike],
    [
      [boolean, bigint, bigint, boolean] & {
        isAuthorized: boolean;
        role: bigint;
        expiry: bigint;
        hasAccess: boolean;
      }
    ],
    "view"
  >;

  hasResponded: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  hasValidAccess: TypedContractMethod<[viewer: AddressLike], [boolean], "view">;

  isActive: TypedContractMethod<[], [boolean], "view">;

  optionsCount: TypedContractMethod<[], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  reopenSurvey: TypedContractMethod<[], [void], "nonpayable">;

  revokeViewer: TypedContractMethod<
    [viewer: AddressLike],
    [void],
    "nonpayable"
  >;

  submitBatchResponse: TypedContractMethod<
    [
      optionIndices: BigNumberish[],
      encryptedVotes: BytesLike[],
      proofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  submitResponse: TypedContractMethod<
    [optionIndex: BigNumberish, encryptedVote: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  surveyDeadline: TypedContractMethod<[], [bigint], "view">;

  surveyDescription: TypedContractMethod<[], [string], "view">;

  surveyTitle: TypedContractMethod<[], [string], "view">;

  withdrawAndResubmit: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "authorizeViewer"
  ): TypedContractMethod<[viewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizeViewerWithRole"
  ): TypedContractMethod<
    [viewer: AddressLike, role: BigNumberish, expiryTimestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "authorizedViewers"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "closeSurvey"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "extendDeadline"
  ): TypedContractMethod<[newDeadline: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllEncryptedTallies"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTally"
  ): TypedContractMethod<[optionIndex: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getOptionLabel"
  ): TypedContractMethod<[optionIndex: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getResultSummary"
  ): TypedContractMethod<
    [],
    [
      [bigint[], string[], bigint] & {
        optionIndices: bigint[];
        optionLabels: string[];
        totalParticipants: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSurveyMetadata"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, boolean, bigint, string, bigint] & {
        title: string;
        description: string;
        optionCount: bigint;
        active: boolean;
        deadline: bigint;
        adminAddr: string;
        viewerCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSurveyStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        totalOptions: bigint;
        activeStatus: bigint;
        deadline: bigint;
        participantCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTopOptions"
  ): TypedContractMethod<[count: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserVotes"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getViewerDetails"
  ): TypedContractMethod<
    [viewer: AddressLike],
    [
      [boolean, bigint, bigint, boolean] & {
        isAuthorized: boolean;
        role: bigint;
        expiry: bigint;
        hasAccess: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasResponded"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasValidAccess"
  ): TypedContractMethod<[viewer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "optionsCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reopenSurvey"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeViewer"
  ): TypedContractMethod<[viewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitBatchResponse"
  ): TypedContractMethod<
    [
      optionIndices: BigNumberish[],
      encryptedVotes: BytesLike[],
      proofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitResponse"
  ): TypedContractMethod<
    [optionIndex: BigNumberish, encryptedVote: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "surveyDeadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "surveyDescription"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "surveyTitle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "withdrawAndResubmit"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "BatchResponseSubmitted"
  ): TypedContractEvent<
    BatchResponseSubmittedEvent.InputTuple,
    BatchResponseSubmittedEvent.OutputTuple,
    BatchResponseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ResponseSubmitted"
  ): TypedContractEvent<
    ResponseSubmittedEvent.InputTuple,
    ResponseSubmittedEvent.OutputTuple,
    ResponseSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyActivated"
  ): TypedContractEvent<
    SurveyActivatedEvent.InputTuple,
    SurveyActivatedEvent.OutputTuple,
    SurveyActivatedEvent.OutputObject
  >;
  getEvent(
    key: "SurveyClosed"
  ): TypedContractEvent<
    SurveyClosedEvent.InputTuple,
    SurveyClosedEvent.OutputTuple,
    SurveyClosedEvent.OutputObject
  >;
  getEvent(
    key: "ViewerAuthorized"
  ): TypedContractEvent<
    ViewerAuthorizedEvent.InputTuple,
    ViewerAuthorizedEvent.OutputTuple,
    ViewerAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "VoteUpdated"
  ): TypedContractEvent<
    VoteUpdatedEvent.InputTuple,
    VoteUpdatedEvent.OutputTuple,
    VoteUpdatedEvent.OutputObject
  >;

  filters: {
    "BatchResponseSubmitted(address,uint256[],uint256)": TypedContractEvent<
      BatchResponseSubmittedEvent.InputTuple,
      BatchResponseSubmittedEvent.OutputTuple,
      BatchResponseSubmittedEvent.OutputObject
    >;
    BatchResponseSubmitted: TypedContractEvent<
      BatchResponseSubmittedEvent.InputTuple,
      BatchResponseSubmittedEvent.OutputTuple,
      BatchResponseSubmittedEvent.OutputObject
    >;

    "ResponseSubmitted(address,uint256)": TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;
    ResponseSubmitted: TypedContractEvent<
      ResponseSubmittedEvent.InputTuple,
      ResponseSubmittedEvent.OutputTuple,
      ResponseSubmittedEvent.OutputObject
    >;

    "SurveyActivated()": TypedContractEvent<
      SurveyActivatedEvent.InputTuple,
      SurveyActivatedEvent.OutputTuple,
      SurveyActivatedEvent.OutputObject
    >;
    SurveyActivated: TypedContractEvent<
      SurveyActivatedEvent.InputTuple,
      SurveyActivatedEvent.OutputTuple,
      SurveyActivatedEvent.OutputObject
    >;

    "SurveyClosed()": TypedContractEvent<
      SurveyClosedEvent.InputTuple,
      SurveyClosedEvent.OutputTuple,
      SurveyClosedEvent.OutputObject
    >;
    SurveyClosed: TypedContractEvent<
      SurveyClosedEvent.InputTuple,
      SurveyClosedEvent.OutputTuple,
      SurveyClosedEvent.OutputObject
    >;

    "ViewerAuthorized(address)": TypedContractEvent<
      ViewerAuthorizedEvent.InputTuple,
      ViewerAuthorizedEvent.OutputTuple,
      ViewerAuthorizedEvent.OutputObject
    >;
    ViewerAuthorized: TypedContractEvent<
      ViewerAuthorizedEvent.InputTuple,
      ViewerAuthorizedEvent.OutputTuple,
      ViewerAuthorizedEvent.OutputObject
    >;

    "VoteUpdated(address,uint256[],uint256[])": TypedContractEvent<
      VoteUpdatedEvent.InputTuple,
      VoteUpdatedEvent.OutputTuple,
      VoteUpdatedEvent.OutputObject
    >;
    VoteUpdated: TypedContractEvent<
      VoteUpdatedEvent.InputTuple,
      VoteUpdatedEvent.OutputTuple,
      VoteUpdatedEvent.OutputObject
    >;
  };
}
